# Generated by Django 3.2.2 on 2021-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='StoreName',
            field=models.TextField(),
        ),
    ]
