# Generated by Django 3.2.2 on 2021-07-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_userprofileinfo_storename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='StoreName',
            field=models.CharField(max_length=300),
        ),
    ]
